ALTER TABLE public.user_tracks
  ADD COLUMN IF NOT EXISTS source text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS spotify_url text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS spotify_id text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS item_type text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS subtitle text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS image text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS metadata_fetched_at timestamptz DEFAULT NULL;